http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
server:
  session-timeout: 3600
  port: 8080
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #环境配置
  profiles: 
    #生产环境
    #active: prod
    #开发环境
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  devtools:
    restart:
      enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.jdm.**.domain

